# Generated by Django 6.0.3 on 2026-06-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='sidebar_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='tickets_per_page',
            field=models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (50, '50')], default=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro'), ('system', 'Sistema')], default='dark', max_length=10),
        ),
    ]
