# Generated by Django 6.0.3 on 2026-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_phone1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
